name: Generate Snake

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Coolbuddy145
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push to main branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "Generate snake animation"
          add: "dist/github-contribution-grid-snake.svg"
          branch: main

